# Generated by Django 3.0.5 on 2020-04-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200416_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedsmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='fricle/images/'),
        ),
    ]
