# Generated by Django 3.0.5 on 2020-04-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200416_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsmodel',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='feedsmodel',
            name='upvote',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='feedsmodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
