# Generated by Django 3.0.5 on 2020-04-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200417_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedsmodel',
            name='comment',
        ),
        migrations.AddField(
            model_name='feedsmodel',
            name='upvoter',
            field=models.TextField(blank=True),
        ),
    ]
