# Generated by Django 3.0.5 on 2020-04-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='receiver',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
