# Generated by Django 3.0.5 on 2020-04-19 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0002_auto_20200419_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='message',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
