# Generated by Django 3.0.5 on 2020-04-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20200419_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='receiver',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
